# Generated by Django 5.2.2 on 2025-06-14 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diagnostic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(editable=False)),
                ('result', models.CharField(choices=[(300, 'vos risques de présenter dans un avenir proche, une maladie somatique, sont très élevés. Un score de 300 et plus suppose que vous avez eu à traverser une série de situations particulièrement pénibles et éprouvantes. Ne craignez donc pas de vous faire aider si c’est votre cas.'), (100, 'Les risques que se déclenche une éventuelle maladie somatique demeure statistiquement significatif. Prenez soin de vous. Ce n’est pas la peine d’en rajouter.'), (0, 'Le risque se révèle peu important. La somme des stress rencontrés en une année est trop peu importante pour ouvrir la voie à une maladie somatique.')], editable=False, max_length=350)),
                ('diagnosticDate', models.DateTimeField()),
                ('diagnosticUser', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
