# Generated by Django 5.2.2 on 2025-06-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0003_information_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='publicationDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
