# Generated by Django 5.2.2 on 2025-06-18 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0004_alter_information_publicationdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='author',
        ),
    ]
