# Generated by Django 5.2.2 on 2025-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0005_remove_information_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='alt',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='information',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='information',
            name='content',
            field=models.CharField(max_length=1000),
        ),
    ]
