# Generated by Django 5.2.2 on 2025-06-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0006_information_alt_information_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=models.CharField(max_length=2000),
        ),
    ]
