# Generated by Django 5.2.2 on 2025-06-21 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0007_alter_information_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='content',
            field=models.CharField(max_length=5000),
        ),
    ]
