# Generated by Django 5.2.2 on 2025-06-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0008_alter_information_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostic',
            name='diagnosticDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='result',
            field=models.TextField(editable=False),
        ),
    ]
