# Generated by Django 5.2.2 on 2025-06-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0009_alter_diagnostic_diagnosticdate_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
