# Generated by Django 5.2.2 on 2025-06-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0010_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='StressEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('score', models.PositiveIntegerField()),
            ],
        ),
    ]
