# Generated by Django 5.2.2 on 2025-06-22 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0011_stressevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosticResultLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(help_text='Minimum score for this level, inclusive.')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['min_score'],
            },
        ),
    ]
