# Generated by Django 5.2.2 on 2025-06-22 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0012_diagnosticresultlevel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosticResultLevel',
        ),
    ]
