# Generated by Django 5.2.2 on 2025-06-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0015_remove_results_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Diagnostic',
        ),
    ]
