# Generated by Django 5.2.2 on 2025-06-22 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0017_category_alter_information_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='category_fk',
        ),
        migrations.AlterField(
            model_name='information',
            name='category',
            field=models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='cesizenapp.category'),
        ),
    ]
