# Generated by Django 5.2.2 on 2025-06-23 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cesizenapp', '0019_alter_information_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='category',
            field=models.CharField(choices=[('SANTE-MENTAL', 'Comprendre la santé mentale'), ('RECONNAITRE-LE-STRESS', 'Reconnaître le stress'), ('GESTION-DU-STRESS', 'Techniques de gestion du stress'), ('COMPTRENDRE-EMOTIONS', 'Comprendre ses émotions'), ('HABITUDES', 'Habitude de vie et auto-soin'), ('ACTIVITES', 'Activités de détente'), ('DEMANDER-L-AIDE', 'Quand demander de l`aide'), ('SOUTENIR', 'Soutenir un proche')], default='DRAFT', max_length=200),
        ),
    ]
